### ISSUE TITLE
Will you update the archive again？

### ISSUE THREAD

**Issue by Kukuair** [HexagonWin/iz-gone#1]
Hello, here WIZ*ONE From China. I also have an archive file of "iz-one.co.kr", but some errors occurred during the crawling, which caused some files to be lost. The local iz-one.co.kr could not be reproduced. I am glad to see that you have the full version of iz-one.co.kr backup. I am curious what tool do you use for crawler backup? and will you update the archive again？

Here is the archive file I Crawled down: https://drive.google.com/file/d/1tm6BklZd7uXMxM5TTjNlyhLe7e5pG1_p/view?usp=sharing

**Comment by HexagonWin** [comment]
Hello, I will upload soon, Thank you. 
However I am having trouble loggon into my google drive, please wait a bit or maybe i will upload it. Thank you

**Comment by HexagonWin** [comment]
Hello, I uploaded the folder in this git repository. Please see if you can clone and launch it properly, and I will close this issue if it's fixed. Thank you.

I used wget -r and some more parameters for it, you can see the script i used on ./iz-home/crawl file.

This is a tip, when you crawl a site, you should also try looking for cdn servers they have, as many site store image and medias in another url, so in this case cdn.iz-one.co.kr

Also for cdn, I recommend downloading cdn.iz-one.co.kr using wayback_machine_downloader (search in github, it's a ruby program) because wayback machine has stored this cdn.iz-one.co.kr since 2018~2021 and with just crawling the site we can only get the latest images on the site because cdn directory listing is not possible. (They still had those old images stored on their site, however the wayback machine has them all so I didn't manual download it)

**Comment by Kukuair** [comment]
I have always used the internet download manager for site crawling. 
Thank you for telling me that, and of course you can close this issue.
I wish you a happy Dragon Boat Festival in advance 🍙

**Comment by HexagonWin** [comment]
Thanks, issue closing.

**Comment by HexagonWin** [comment]
Addition : IZ* One homepages can now be viewed thanks to the iz-web-project. Please check out https://ahisky.github.io/izwb/

**Comment by Kukuair** [comment]
Thank you!
